spring:
  application:
    name: disc-jockey-console
  graphql:
    graphiql:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/djconsole
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        type:
          json_format_mapper: com.github.fbascheper.dj.console.bootstrap.hibernate.CustomJacksonJsonFormatMapper

logging:
  level:
    graphql:
      execution: DEBUG
    com.github.fbascheper: DEBUG
    org.hibernate.SQL: INFO
    org.hibernate.orm.json: DEBUG
